FROM alpine
MAINTAINER Aram Zadikian <if@else.run>

RUN apk add --no-cache wget
RUN apk add --no-cache ca-certificates

RUN wget https://github.com/papertrail/remote_syslog2/releases/download/v0.18/remote_syslog_linux_i386.tar.gz; \
	tar -xf ./remote_syslog_linux_i386.tar.gz; \
	cp ./remote_syslog/remote_syslog /usr/local/bin; \
	rm -rf ./remote_syslog; \
	rm remote_syslog_linux_i386.tar.gz
