FROM python
MAINTAINER Aram Zadikian <if@else.run>

RUN apt-get update && apt-get install -y \
	postgresql-client \
	--no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

ENV APP_PATH /app/in-spiritus
RUN mkdir -p $APP_PATH
WORKDIR $APP_PATH

COPY docker/tools/stellar/stellar.yaml $APP_PATH/

RUN pip install psycopg2
RUN pip install stellar
